/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *  File Name:  Chess
 *  Programmer: Sherwin Varkiani
 *  Date:       6/18/2017
 *  Description:This file swaps between the jFrames. Overall, this program is a chess game that has both singleplayer and multiplayer chess capabilities. It also has a high score system.
 */
public class Chess extends javax.swing.JFrame {

    /**
     * Creates new form Chess
     */
    public Chess() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        SingleplayerButton = new javax.swing.JButton();
        MultiplayerButton = new javax.swing.JButton();
        HighScoresButton = new javax.swing.JButton();
        AuthorLabel = new javax.swing.JLabel();
        ImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        TitleLabel.setText("Chess");

        SingleplayerButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SingleplayerButton.setForeground(new java.awt.Color(51, 51, 255));
        SingleplayerButton.setText("1 Player");
        SingleplayerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SingleplayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleplayerButtonActionPerformed(evt);
            }
        });

        MultiplayerButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MultiplayerButton.setForeground(new java.awt.Color(51, 51, 255));
        MultiplayerButton.setText("2 Player");
        MultiplayerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MultiplayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplayerButtonActionPerformed(evt);
            }
        });

        HighScoresButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        HighScoresButton.setText("Scores");
        HighScoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighScoresButtonActionPerformed(evt);
            }
        });

        AuthorLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AuthorLabel.setText("By: Sherwin Varkiani");

        ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chess.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(SingleplayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MultiplayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImageLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AuthorLabel)
                        .addGap(13, 13, 13)))
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TitleLabel)
                        .addGap(261, 261, 261))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(HighScoresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AuthorLabel)
                .addGap(29, 29, 29)
                .addComponent(ImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SingleplayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MultiplayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(HighScoresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
        Pre-Condition: Activates when the user clicks the 2 Player button
        Post-Condition: Swaps to the multiplayerchess jframe
     */
    private void MultiplayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplayerButtonActionPerformed
        this.setVisible(false);
        new MultiplayerChess().setVisible(true); //switches between jframes
    }//GEN-LAST:event_MultiplayerButtonActionPerformed

    /*
        Pre-Condition: Activates when the user clicks the highscores button
        Post-Condition: Swaps to the highscores jframe
     */
    private void HighScoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighScoresButtonActionPerformed
        this.setVisible(false);
        new Highscores().setVisible(true); //switches between jframes
    }//GEN-LAST:event_HighScoresButtonActionPerformed

    /*
        Pre-Condition: Activates when the user clicks the 1 Player button
        Post-Condition: Swaps to the singleplayer jframe
     */
    private void SingleplayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleplayerButtonActionPerformed
        this.setVisible(false);
        new SingleplayerChess().setVisible(true); //switches between jframes
    }//GEN-LAST:event_SingleplayerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorLabel;
    private javax.swing.JButton HighScoresButton;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JButton MultiplayerButton;
    private javax.swing.JButton SingleplayerButton;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
}
